version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rag-app
    restart: unless-stopped
    ports:
      - "${STREAMLIT_SERVER_PORT:-8501}:8501"
    env_file:
      - .env
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./scripts:/app/scripts
    depends_on:
      - ollama
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  ollama:
    image: ollama/ollama:latest
    container_name: ollama-service
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - rag-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  init-models:
    image: curlimages/curl:latest
    container_name: ollama-model-init
    depends_on:
      ollama:
        condition: service_healthy
    restart: on-failure
    networks:
      - rag-network
    volumes:
      - ./scripts:/scripts
    entrypoint: ["/bin/sh", "/scripts/init_models.sh"]

volumes:
  ollama-data:
    driver: local

networks:
  rag-network:
    driver: bridge 