"""Configuration for language models."""

OLLAMA_MODEL_ID = "deepseek-r1:1.5b"

AVAILABLE_MODELS = ["qwen2.5-coder:3b", "qwen2.5:3b", "deepseek-r1:1.5b"]

DEFAULT_MODEL_INDEX = 2

DEFAULT_TEMPERATURE = 0.5
MIN_TEMPERATURE = 0.0
MAX_TEMPERATURE = 1.0
TEMPERATURE_STEP = 0.1

MIN_TOP_K = 1
MAX_TOP_K = 10
DEFAULT_TOP_K = 3

DEFAULT_MAX_TOKENS = 512
MIN_MAX_TOKENS = 64
MAX_MAX_TOKENS = 2048
MAX_TOKENS_STEP = 64

DEFAULT_TOP_P = 0.9
MIN_TOP_P = 0.1
MAX_TOP_P = 1.0
TOP_P_STEP = 0.05
